Fix `-Wcomment` and `-Wreturn-type` warnings (#109)
gcc complained about one comment in `layer_utils.h`:
```
/performance-layers/layer/layer_utils.h:163:1: error: multi-line comment [-Werror=comment]
  163 | //    #define SPL_MY_LAYER_FUNC(RETURN_TYPE_, FUNC_NAME_, FUNC_ARGS_)   \
      | ^
```

and a missing return in a switch in `input_buffer.cc`. This fixes these
warnings and enables them in the CI.

Fixes: https://github.com/google/vulkan-performance-layers/issues/104